### ISSUE TITLE
When we click on add another the membership setting there is message “please purchase pro” when we click add another button no. Of times then it will show that message that no. Of time

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#10]
Bug name:When we click on add another the membership setting there is message “please purchase pro” when we click add another button no. Of times then it will show that message that no. Of time
Area Path: admin-dashboard>woocommerce>rewardeem woocommerce points and rewards>membership tab>click add another
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:-
![screenshot-localhost-2019 09 03-11_15_25](https://user-images.githubusercontent.com/48902379/64146899-45727780-ce3c-11e9-9507-fb7903fba757.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed
