### ISSUE TITLE
There is a remove button which is not any use in membership tab

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#11]
Bug name:no use of remove button
Area Path: admin-dashboard>woocommerce>rewardeem woocommerce points and rewards>general>Enter Ways to Gain Points
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:-
![screenshot-localhost-2019 09 03-11_22_20](https://user-images.githubusercontent.com/48902379/64147216-33dd9f80-ce3d-11e9-9656-2b35a63e2ea7.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed this button is used for removing the current membership level.

**Comment by cedcoss-pooja** [comment]
but after refresh the page removed level again show
