### ISSUE TITLE
There is error for undefined  error  when we  use current membership shortcode

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#12]
Bug name:when we used shortcode current membership it show some undefined error
Area Path: frontend>myaccountpage
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:-
![screenshot-localhost-2019 08 25-14_07_53(3)](https://user-images.githubusercontent.com/48902379/64147403-c716d500-ce3d-11e9-9501-eddcbe262e28.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed
