### ISSUE TITLE
[SIGNUPNOTIFICATION] shortcode is not working

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#13]
Bug name:[SIGNUPNOTIFICATION] shortcode is not apply when we add it any page
Area Path: frontend>my account page
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:-[SIGNUPNOTIFICATION] shortcode is not working

**Comment by mohitmishra-cedcoss** [comment]
Fixed
