### ISSUE TITLE
Total point of the point log table seems very dimnished

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#15]
Bug name:total point in point log table is show very small
Area Path: frontend>my account page
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:-
![screenshot-localhost-2019 09 03-11_46_31](https://user-images.githubusercontent.com/48902379/64148463-fda21f00-ce40-11e9-8569-324c428256a7.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by cedcoss-pooja** [comment]
not fixed
