### ISSUE TITLE
Need to remove "Rewardeem" and "Lite" from the plugin

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#16]
Need to remove "Rewardeem" and "Lite" from the plugin
![image](https://user-images.githubusercontent.com/25762796/64173005-e92b4a00-ce73-11e9-8457-c52522b1333c.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
