### ISSUE TITLE
Remove "Coupon Details" under Points Table tab

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#17]
No feature is related to coupon in this plugin. Remove coupon details.
![image](https://user-images.githubusercontent.com/25762796/64173774-a10d2700-ce75-11e9-9260-0075a8f60aa8.png)

**Comment by mohitmishra-cedcoss** [comment]
This will list all the coupons generated by the user

**Comment by anshucedcoss** [comment]
This feature  is in PRO plugin

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
