### ISSUE TITLE
There are some typos in the notification settings

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#18]
There are some typos in the notification settings.
![image](https://user-images.githubusercontent.com/25762796/64234375-d2d4cb00-cf13-11e9-89fd-40810c07f55d.png)

**Comment by anshucedcoss** [comment]
![image](https://user-images.githubusercontent.com/25762796/68199313-d227e600-ffe3-11e9-9637-ec85e2887318.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
Done
