### ISSUE TITLE
" Ways to Gain Points" should be blank by defult

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#19]
" Ways to Gain Points" should be blank by default.
![image](https://user-images.githubusercontent.com/25762796/64234653-68705a80-cf14-11e9-9718-336d13107a6e.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
