### ISSUE TITLE
Mail is not correct send when custom point notification is send “upadated amount is not  correct” means it show last updated amount

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#20]
Bug name:Mail is not correct send when custom point notification is send “upadated amount is not  correct” means it show last updated amount
Area Path: frontend>email
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:- when custom point notification is send “upadated amount is not  correct” means it show last updated amount

**Comment by mohitmishra-cedcoss** [comment]
fixed
