### ISSUE TITLE
Membership mail is not recevied

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#22]
Bug name:when membership upgraded it mail is not send 
Area Path: frontend>email
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:-membership related mail is not send

**Comment by mohitmishra-cedcoss** [comment]
fixed

**Comment by cedcoss-pooja** [comment]
not fixed

**Comment by cedcoss-pooja** [comment]
done
