### ISSUE TITLE
Global Product Points setting  is not disable

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#23]
Bug name:when we try to disable the setting of global product point then it will automatically enable
Area Path: frontend>my account page
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:-when we try to disable the setting of global product point then it will automatically enable

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by cedcoss-pooja** [comment]
having new issues 
![screenshot-192 168 1 184-2019 10 10-19_04_13](https://user-images.githubusercontent.com/48902379/66573790-dbfb2c80-eb90-11e9-8a98-13f22c58c650.png)

**Comment by cedcoss-pooja** [comment]
sir please have a look above screenshot in global setting the description of both the setting is same

**Comment by cedcoss-pooja** [comment]
done
