### ISSUE TITLE
other total point is not working 

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#24]
Bug name:-other point setting is not work 
Area Path: frontend>my account page
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:-when we enable the setting of  other point setting  it will not work

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by cedcoss-pooja** [comment]
Not working

**Comment by mohitmishra-cedcoss** [comment]
Working Fine
