### ISSUE TITLE
Same description is written all notifications description.

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#25]
The appropriate description should be written in each notification description.
![image](https://user-images.githubusercontent.com/25762796/64235841-d289ff00-cf16-11e9-8bde-e20cda1027ff.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
