### ISSUE TITLE
"Enable apply points during checkout" will work only when "Redemption Over Cart Sub-Total" setting is enabled

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#27]
"Enable apply points during checkout" will work only when "Redemption Over Cart Sub-Total" setting is enabled
![image](https://user-images.githubusercontent.com/25762796/64237410-ee42d480-cf19-11e9-9b12-c33a222d15cd.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
