### ISSUE TITLE
Need to change the description of "Redemption Over Cart Sub-Total"

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#28]
Need to change the description of "Redemption Over Cart Sub-Total"
![image](https://user-images.githubusercontent.com/25762796/64255520-2a3c6080-cf3f-11e9-8cb4-25951b89ec0d.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
