### ISSUE TITLE
"Apply Points" textbox should display like "Apply Coupon" Textbox

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#30]
"Apply Points" textbox should display like "Apply Coupon" Textbox on Cart/Checkout.

![image](https://user-images.githubusercontent.com/25762796/64256062-48ef2700-cf40-11e9-91de-be911fdda6fd.png)

![image](https://user-images.githubusercontent.com/25762796/64256145-720fb780-cf40-11e9-9de2-d4209d7b58ba.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
Not fixed yet

**Comment by anshucedcoss** [comment]
Need to modify

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
