### ISSUE TITLE
"Earn Points Per Currency Settings " should display in "General" Settings

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#31]
"Earn Points Per Currency Settings " should display in "General" Settings
![image](https://user-images.githubusercontent.com/25762796/64259977-bb173a00-cf47-11e9-9e8a-91f59d02dd5a.png)

**Comment by anshucedcoss** [comment]
Coupons Settings will only get display when the "PRO" plugin is activated.
![image](https://user-images.githubusercontent.com/25762796/68367718-556c4780-015c-11ea-82cd-75f5ef1f838e.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed
