### ISSUE TITLE
No need of "Expiry for Old Users" button under "Membership" tab

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#33]
No need of "Expiry for Old Users" button under "Membership" tab.
![image](https://user-images.githubusercontent.com/25762796/64262125-3d552d80-cf4b-11e9-8b3e-2022ac94f10d.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
