### ISSUE TITLE
Product Name should also display on the Membership discount pop-up

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#34]
Product Name should also display on the Membership discount pop-up
![image](https://user-images.githubusercontent.com/25762796/64267108-6c6f9d00-cf53-11e9-8663-32218fa7825c.png)

**Comment by mohitmishra-cedcoss** [comment]
fixed

**Comment by anshucedcoss** [comment]
"View Benefit" button is't working now

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
