### ISSUE TITLE
When update Points under "Points Table" then Confirmation message should display

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#35]
When update Points under "Points Table" then Confirmation message should display.
![image](https://user-images.githubusercontent.com/25762796/64267246-b0fb3880-cf53-11e9-8326-854fb9757632.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
