### ISSUE TITLE
Wrong Total  Poinst are displaying in Cutom Point Notification Email

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#36]
Wrong Total  Poinst are displaying in Cutom Point Notification Email
![image](https://user-images.githubusercontent.com/25762796/64267533-354dbb80-cf54-11e9-9b2c-70218cd20947.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
