### ISSUE TITLE
IF user has no any points then points should display 0 under "Points Table"

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#37]
IF user has no any points then points should display 0 under "Points Table"
![image](https://user-images.githubusercontent.com/25762796/64403789-8619fd00-d097-11e9-8cdd-f93d556e7cb3.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
