### ISSUE TITLE
Membership Pop will get display according to the no. of categories

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#38]
Membership Pop will get display according to the no. of categories selected for discount.
![image](https://user-images.githubusercontent.com/25762796/64404230-e198ba80-d098-11e9-905f-4053489cbf31.png)

**Comment by mohitmishra-cedcoss** [comment]
Working fine

**Comment by anshucedcoss** [comment]
Some extra space is displaying in the pop-up.

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
