### ISSUE TITLE
When upgrading membership level by the customer then the warning message should get the display

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#39]
When upgrading membership level by the customer then the warning message should get the display.
![image](https://user-images.githubusercontent.com/25762796/64404413-81564880-d099-11e9-85f0-1a48538cf2b8.png)

**Comment by mohitmishra-cedcoss** [comment]
done

**Comment by anshucedcoss** [comment]
Fixed
