### ISSUE TITLE
During activation of plugin there is error

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#4]
Bug name:-When we activate the plugin then it show an error 
Area Path: admin-dashboard>plugin>ultimate woocommerce points and reward>actviate
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:When we activate the plugin it show some fatel error

Warning: require_once(/opt/lampp/htdocs/wordpressfolder/NewRMA/wp-content/plugins/ultimate-woocommerce-points-and-rewards-version1.0.0/includes/class-rewardeem-woocommerce-points-rewards-activator.php): failed to open stream: No such file or directory in /opt/lampp/htdocs/wordpressfolder/NewRMA/wp-content/plugins/ultimate-woocommerce-points-and-rewards-version1.0.0/rewardeem-woocommerce-points-rewards.php on line 90

Fatal error: require_once(): Failed opening required '/opt/lampp/htdocs/wordpressfolder/NewRMA/wp-content/plugins/ultimate-woocommerce-points-and-rewards-version1.0.0/includes/class-rewardeem-woocommerce-points-rewards-activator.php' (include_path='.:/opt/lampp/lib/php') in /opt/lampp/htdocs/wordpressfolder/NewRMA/wp-content/plugins/ultimate-woocommerce-points-and-rewards-version1.0.0/rewardeem-woocommerce-points-rewards.php on line 90

**Comment by mohitmishra-cedcoss** [comment]
Fixed
