### ISSUE TITLE
After Upgrading the membership level, "Select Roles" option should not display

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#40]
After Upgrading the membership level, "Select Roles" option should not display.
![image](https://user-images.githubusercontent.com/25762796/64404566-fa55a000-d099-11e9-96fa-61880e20632b.png)

**Comment by mohitmishra-cedcoss** [comment]
fixed

**Comment by anshucedcoss** [comment]
If there is a single membership level then after updating the memebership level "Select Roles" will not get display.
