### ISSUE TITLE
Need to change "Select Roles" drop-down name. It should be like "Select Membership"

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#41]
Need to change "Select Roles" drop-down name. It should be like "Select Membership"
![image](https://user-images.githubusercontent.com/25762796/64404669-47397680-d09a-11e9-9698-45eabe034f64.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
Not Fixed Yet

**Comment by mohitmishra-cedcoss** [comment]
if we will do this then the appereance will be bad

**Comment by anshucedcoss** [comment]
OKay
