### ISSUE TITLE
Referral link shoud display full width of Box

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#42]
Referral link should display the full width of Box in Customer Dashboard.
![image](https://user-images.githubusercontent.com/25762796/64404751-8b2c7b80-d09a-11e9-997a-f104c6fb4419.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
