### ISSUE TITLE
"Membership Discount" is not applying on the Variable Products

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#44]
"Membership Discount" is not applying on the Variable Products.
![image](https://user-images.githubusercontent.com/25762796/64405350-718c3380-d09c-11e9-8b8a-65a379f156b2.png)

**Comment by mohitmishra-cedcoss** [comment]
This is a pro  feature

**Comment by anshucedcoss** [comment]
Okay.
