### ISSUE TITLE
"Assigin Product Points" are not disabling from backend

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#45]
"Assigin Product Points" are not disabling from the backend
![image](https://user-images.githubusercontent.com/25762796/64405774-ab116e80-d09d-11e9-951a-7b5495d85d04.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
