### ISSUE TITLE
Product  Points are not assigning to variable products

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#46]
Product  Points are not assigning to variable products

![image](https://user-images.githubusercontent.com/25762796/64406206-dfd1f580-d09e-11e9-87f6-2754f3245d7e.png)

**Comment by mohitmishra-cedcoss** [comment]
This feature is included in the pro version

**Comment by anshucedcoss** [comment]
OKAY
