### ISSUE TITLE
"Updating Failed" message is displaying when enter the shortcode on any post or page

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#47]
"Updating Failed" message is displaying when entering the shortcode on any post or page

![image](https://user-images.githubusercontent.com/25762796/64407119-288aae00-d0a1-11e9-8a0d-2cb163cfaef2.png)

**Comment by mohitmishra-cedcoss** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
