### ISSUE TITLE
Points should not display to the guest user 

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#48]
Points are displaying to the guest user when entering the shortcode.
![image](https://user-images.githubusercontent.com/25762796/64407617-5fad8f00-d0a2-11e9-8616-e07e80658961.png)

**Comment by mohitmishra-cedcoss** [comment]
Working fine

**Comment by anshucedcoss** [comment]
Okay
