### ISSUE TITLE
Social link(facbook,email,twitter) is not shown when we share the link

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#5]
Bug name:social link is not shown when we enable the plugin
Area Path: admin-dashboard>woocommerce>rewardeem woocommerce points and rewards>general>Select Social Links
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:
![screenshot-localhost-2019 09 02-19_26_20](https://user-images.githubusercontent.com/48902379/64119520-aefc7280-cdb7-11e9-8034-04717f2b452d.png)

**Comment by mohitmishra-cedcoss** [comment]
fixed
