### ISSUE TITLE
Need to change " Notification Settings" heading under "Other Settings" tab

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#50]
Need to change " Notification Settings" heading under "Other Settings" tab.
This Heading already exists.
![image](https://user-images.githubusercontent.com/25762796/64408051-72749380-d0a3-11e9-8be4-83a050210ff1.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
Done
