### ISSUE TITLE
Warning Message is displaying when save settings under "Other Settings" tab

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#51]
Warning Message is displaying when saving settings under "Other Settings" tab
![image](https://user-images.githubusercontent.com/25762796/64408232-de56fc00-d0a3-11e9-96bd-2a3f0377740a.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
