### ISSUE TITLE
Notices are displaying in the "Order Total Points"

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#53]
Notices are displaying in the "Order Total Points"

![image](https://user-images.githubusercontent.com/25762796/64409577-d482c800-d0a6-11e9-9096-dbd289eb164d.png)

**Comment by mohitmishra-cedcoss** [comment]
fixed

**Comment by anshucedcoss** [comment]
Done
