### ISSUE TITLE
No need of "Remove" button under "Order Total Points"

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#54]
No need of "Remove" button under "Order Total Points"

![image](https://user-images.githubusercontent.com/25762796/64409785-33484180-d0a7-11e9-90ff-a2ff3d24e6ba.png)

**Comment by mohitmishra-cedcoss** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
