### ISSUE TITLE
Need to change Accordion of "Points Log "

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#56]
Need to change Accordion of "Points Log ". It should be something like
![image](https://user-images.githubusercontent.com/25762796/64411673-5b39a400-d0ab-11e9-8799-b5ec8715f9ad.png)
http://bestjquery.com/tutorial/accordion/demo88/#collapseOne

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
