### ISSUE TITLE
Correct Heading and it's discription should display under "Product Assigin Points"

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#57]
Correct Heading and it's discription should display under "Product Assigin Points"
![image](https://user-images.githubusercontent.com/25762796/64536501-de225f00-d336-11e9-987a-12e56854c38f.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
done
