### ISSUE TITLE
No use of comment shortcode

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#6]
Bug name:-No any requirement of comment shortcode
Area Path: admin-dashboard>woocommerce>rewardeem woocommerce points and rewards>general>Enter Ways to Gain Points
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description: there is no any requirement of comment shortcode
![screenshot-f2ea2a06 ngrok io-2019 09 02-19_30_23](https://user-images.githubusercontent.com/48902379/64119743-2d591480-cdb8-11e9-9568-835318bf9b56.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed
