### ISSUE TITLE
Enter way to gain  point “textarea” at the corner

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#60]
![screenshot-192 168 1 184-2019 09 27-11_59_01](https://user-images.githubusercontent.com/48902379/65754464-be5caa80-e12e-11e9-923b-468dea9e221d.png)

**Comment by cedcoss-pooja** [comment]
not fixed

**Comment by mohitmishra-cedcoss** [comment]
Not an issue

**Comment by mohitmishra-cedcoss** [comment]
![image](https://user-images.githubusercontent.com/41980812/66985180-dabe8800-f0d9-11e9-9e85-b70e52755ad8.png)

**Comment by mohitmishra-cedcoss** [comment]
Showing perfectly
