### ISSUE TITLE
In sign up point notification on the account page there should be space between the points and strings

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#64]
In sign up point notification on the account page there should be space between the points and strings.
![image](https://user-images.githubusercontent.com/25762796/68068450-d7362c80-fd7a-11e9-8b07-13144afe9aad.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
