### ISSUE TITLE
Side Bar is also not displaying properly on My Accounts > Points tab

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#66]
SideBar is also not displaying properly on My Accounts > Points tab
![image](https://user-images.githubusercontent.com/25762796/68115431-629bf300-ff1e-11e9-9b60-ccefbefdc9d7.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
