### ISSUE TITLE
Membership level is displaying twice on the Account Page

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#67]
Membership level is displaying twice on the Account Page.
![image](https://user-images.githubusercontent.com/25762796/68122045-700da900-ff2f-11e9-99df-898f060189b5.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
