### ISSUE TITLE
Left Menu should be fixed while scroll the settings down

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#68]
Left Menu should be fixed while scrolling the settings down.
![image](https://user-images.githubusercontent.com/25762796/68198666-80cb2700-ffe2-11e9-8a34-02844453ed43.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
