### ISSUE TITLE
Membership Log is displaying Blank, When no any user customer in membership

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#69]
Membership Log is displaying Blank. When no any user customer in membership.
The default message should get the display.
![image](https://user-images.githubusercontent.com/25762796/68367144-0245c500-015b-11ea-8b91-24d147a80d51.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
