### ISSUE TITLE
“Enter Ways to Gain Points” all points are merge together there is no any way to show each point in single line

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#7]
Bug name:All new line statement are merge together
Area Path: admin-dashboard>woocommerce>rewardeem woocommerce points and rewards>general>Enter Ways to Gain Points
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:
![screenshot-localhost-2019 09 02-19_26_20 (1)](https://user-images.githubusercontent.com/48902379/64119912-8b85f780-cdb8-11e9-98e8-4b95bcf23b51.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed
