### ISSUE TITLE
Menu Name Should be "Points and Rewards" instead of "Points and Rewards for WooCommerce"

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#70]
Menu Name Should be "Points and Rewards" instead of "Points and Rewards for WooCommerce"
![image](https://user-images.githubusercontent.com/25762796/68368482-22c34e80-015e-11ea-9e0e-e24c5b503e75.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed

**Comment by anshucedcoss** [comment]
DONE
