### ISSUE TITLE
checkout page there is point conversion is not correct

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#8]
Bug name:Where we enter point for applying in checkout page there is incorrect conversion rate is shown
Area Path: frontend>checkout page>
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:
![screenshot-localhost-2019 09 03-10_59_45](https://user-images.githubusercontent.com/48902379/64146482-c892ce00-ce3a-11e9-9b97-c045c20ae162.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed
