### ISSUE TITLE
Membership tab  “enable membership” is not enable or clickable

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/ultimate-woocommerce-points-and-rewards#9]
Bug name:Membership tab setting is not working
Area Path: admin-dashboard>woocommerce>rewardeem woocommerce points and rewards>membership tab
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:-
![screenshot-localhost-2019 09 03-11_11_20](https://user-images.githubusercontent.com/48902379/64146774-d432c480-ce3b-11e9-89ec-2e19ab2da2ff.png)

**Comment by mohitmishra-cedcoss** [comment]
Fixed
